package com.almasix.ide

import java.nio.file.Path

/**
 * Pure planners for Almasix quick-fixes / intentions (create missing view,
 * suggest `smith make:*`, etc.).
 */
object AlmasixCodeActionPlanner {
    data class Action(
        val id: String,
        val title: String,
        val kind: SymbolKind,
        val name: String,
        /** Absolute path of a file to create (when applicable). */
        val createPath: String? = null,
        /** Arguments for `smith` (e.g. `make:view auth.login`). */
        val smithArgs: String? = null,
    )

    /**
     * Suggest fixes when [name] is an unknown symbol of [kind] under [index].
     * Empty when the symbol is known / blank / unsupported.
     */
    fun forUnknownSymbol(index: AlmasixIndex, kind: SymbolKind, name: String): List<Action> {
        if (name.isBlank()) return emptyList()
        if (index.known(kind, name)) return emptyList()
        return when (kind) {
            SymbolKind.VIEW -> listOfNotNull(
                createViewAction(index, name),
                smithAction("make:view", name, "Create view via smith make:view $name"),
            )
            SymbolKind.COMPONENT -> listOfNotNull(
                createComponentViewAction(index, name),
                smithAction("make:component", name, "Create component via smith make:component $name"),
            )
            SymbolKind.CONTROLLER_ACTION -> listOf(
                smithAction("make:controller", name.substringBefore('@', name), "Create controller via smith"),
            )
            SymbolKind.MIDDLEWARE -> listOf(
                smithAction("make:middleware", name, "Create middleware via smith make:middleware $name"),
            )
            SymbolKind.MAILER -> listOf(
                smithAction("make:mail", name, "Create mailable via smith make:mail $name"),
            )
            SymbolKind.INERTIA -> emptyList() // pages live in the SPA kit; no single make target
            SymbolKind.ROUTE -> emptyList() // routes are declared in routes/*.py, not generated by name alone
            SymbolKind.CONFIG -> emptyList() // config keys need a file edit, not a stub file
            SymbolKind.ENV -> emptyList()
            else -> emptyList()
        }
    }

    fun viewPathForName(basePath: String, dottedName: String): Path {
        val rel = dottedName.replace('.', '/') + ".prism.html"
        val base = if (basePath.isNotBlank()) Path.of(basePath) else Path.of(".")
        return base.resolve("resources/views").resolve(rel).normalize()
    }

    fun componentPathForName(basePath: String, name: String): Path {
        val rel = name.replace('.', '/') + ".prism.html"
        val base = if (basePath.isNotBlank()) Path.of(basePath) else Path.of(".")
        return base.resolve("resources/views/components").resolve(rel).normalize()
    }

    /** Empty Prism stub body for a newly created view/component. */
    fun stubPrismContent(name: String): String =
        """
        {{-- $name --}}
        
        """.trimIndent()

    private fun createViewAction(index: AlmasixIndex, name: String): Action {
        val path = viewPathForName(index.basePath, name).toString()
        return Action(
            id = "create-view-file",
            title = "Create view [$name]",
            kind = SymbolKind.VIEW,
            name = name,
            createPath = path,
        )
    }

    private fun createComponentViewAction(index: AlmasixIndex, name: String): Action {
        val path = componentPathForName(index.basePath, name).toString()
        return Action(
            id = "create-component-file",
            title = "Create component [$name]",
            kind = SymbolKind.COMPONENT,
            name = name,
            createPath = path,
        )
    }

    private fun smithAction(command: String, name: String, title: String): Action =
        Action(
            id = "smith-$command",
            title = title,
            kind = SymbolKind.SMITH,
            name = name,
            smithArgs = "$command $name",
        )
}
